/* Stillwater on Babylon.js. Orthographic 3D, glTF assets, HDR light, PCSS shadows,
 * engine SSAO/anti-aliasing, real geometric roof tiles and planar water reflections. */
(()=>{
'use strict';
const B=window.BABYLON,T=window.THREE;
let engine;
try{if(!B||!window.StillwaterModels)throw Error('The local game engine is unavailable.');engine=new B.Engine(canvas,true,{preserveDrawingBuffer:true,stencil:true,powerPreference:'high-performance',disableWebGL2Support:false},false);}catch(error){
 const fallback=document.createElement('canvas');fallback.id='fallbackWorld';Object.assign(fallback.style,{position:'absolute',inset:'0',width:'100%',height:'100%',pointerEvents:'none'});canvas.insertAdjacentElement('beforebegin',fallback);canvas.style.opacity='0';worldContext=fallback.getContext('2d');renderTarget=worldContext;const fit=()=>{fallback.width=W*dpr;fallback.height=H*dpr};fit();window.addEventListener('resize',fit);window.spaGraphics={mode:'canvas',engine:'Canvas fallback',ready:true,reason:error.message};toast('Simple visuals are active. Your spa is still playable.');return;
}
const scene=new B.Scene(engine);scene.useRightHandedSystem=true;scene.clearColor=new B.Color4(.69,.81,.83,1);scene.ambientColor=B.Color3.Black();scene.environmentIntensity=.65;
const view=new B.UniversalCamera('Isometric orbit',new B.Vector3(-80,100,80),scene);view.mode=B.Camera.ORTHOGRAPHIC_CAMERA;view.minZ=.1;view.maxZ=1000;scene.activeCamera=view;
const sun=new B.DirectionalLight('Sun',new B.Vector3(.5,-1,-.4),scene);sun.position=new B.Vector3(-16,28,14);sun.intensity=3.4;sun.diffuse=B.Color3.FromHexString('#fff1da');sun.autoCalcShadowZBounds=true;sun.autoUpdateExtends=true;sun.shadowOrthoScale=.16;
const sky=new B.HemisphericLight('Sky fill',B.Vector3.Up(),scene);sky.intensity=.25;sky.diffuse=B.Color3.FromHexString('#e3eff3');sky.groundColor=B.Color3.FromHexString('#5d6859');
const shadows=new B.ShadowGenerator(2048,sun);shadows.useContactHardeningShadow=true;shadows.contactHardeningLightSizeUVRatio=.025;shadows.bias=.0003;shadows.normalBias=.015;shadows.getShadowMap().refreshRate=0;
const library=StillwaterModels.create(),sourceScene=new T.Group(),objectSources=new T.Group(),floorSources=new T.Group(),guestSources=new T.Group();sourceScene.add(library.art.root,objectSources,floorSources,guestSources);
const geometryCache=new Map(),materialCache=new Map(),textureCache=new Map(),containers=new Map(),objectModels=new Map(),sourceObjects=new Map(),guestMeshes=new Map(),guestBatches=new Map(),guestNodes=new Map();
const records=new Set();let landscape=null,floorWorld=null,indicator=null,ghost=null,floorStamp='',objectStamp='',indicatorStamp='',revision=0,theme='morning',quality='balanced',roofMode='cutaway',settled=false,ready=false,lastDraw=0,elapsed=0,sizedW=0,sizedH=0,worldDistance=160,importInstances=0,ssao=null,pipeline=null,assetRevision=0;
const scratch=new T.Object3D(),guestRoot=new T.Group(),guestBatchRoot=guestSources;
function color(hex){return B.Color3.FromHexString(hex)}
function bytes(key){const raw=atob(STILLWATER_ASSETS[key].data),data=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)data[i]=raw.charCodeAt(i);return data;}
function markShadows(){const map=shadows.getShadowMap();if(map)map.resetRefreshCounter();}
function normalFromHeight(image,strength=3){const c=document.createElement('canvas');c.width=image.width||512;c.height=image.height||512;const q=c.getContext('2d');q.drawImage(image,0,0);const data=q.getImageData(0,0,c.width,c.height),out=q.createImageData(c.width,c.height),w=c.width,h=c.height;const sample=(x,y)=>data.data[(((y+h)%h)*w+(x+w)%w)*4]/255;for(let y=0;y<h;y++)for(let x=0;x<w;x++){let dx=(sample(x-1,y)-sample(x+1,y))*strength,dy=(sample(x,y-1)-sample(x,y+1))*strength,n=Math.sqrt(dx*dx+dy*dy+1),i=(y*w+x)*4;out.data[i]=(dx/n*.5+.5)*255;out.data[i+1]=(dy/n*.5+.5)*255;out.data[i+2]=(1/n*.5+.5)*255;out.data[i+3]=255}q.putImageData(out,0,0);return c;}
function texture(src,normal=false){const id=src.uuid+(normal?':normal':'');if(textureCache.has(id))return textureCache.get(id);let image=src.image;if(!image)return null;if(normal)image=normalFromHeight(image,src===library.art.roofAtlas?4:2);let url;if(image.toDataURL)url=image.toDataURL('image/png');else{const c=document.createElement('canvas');c.width=image.width;c.height=image.height;c.getContext('2d').drawImage(image,0,0);url=c.toDataURL('image/png');}const tex=new B.Texture(url,scene,false,true,B.Texture.TRILINEAR_SAMPLINGMODE);tex.gammaSpace=!normal;tex.anisotropicFilteringLevel=8;tex.wrapU=tex.wrapV=B.Texture.WRAP_ADDRESSMODE;tex.uScale=src.repeat?.x||1;tex.vScale=src.repeat?.y||1;textureCache.set(id,tex);return tex;}
const waterNormalCanvas=document.createElement('canvas');waterNormalCanvas.width=waterNormalCanvas.height=128;const wnq=waterNormalCanvas.getContext('2d'),wnd=wnq.createImageData(128,128);for(let z=0;z<128;z++)for(let x=0;x<128;x++){const i=(z*128+x)*4;wnd.data[i]=128+Math.sin(x*.31+Math.sin(z*.12))*22;wnd.data[i+1]=128+Math.cos(z*.29+Math.sin(x*.1))*18;wnd.data[i+2]=250;wnd.data[i+3]=255;}wnq.putImageData(wnd,0,0);const waterNormal=new B.Texture(waterNormalCanvas.toDataURL(),scene,false,false);waterNormal.gammaSpace=false;waterNormal.uScale=waterNormal.vScale=5;
function material(src){if(materialCache.has(src.uuid))return materialCache.get(src.uuid);const kind=src.userData?.kind,m=new B.PBRMaterial('Surface '+(kind||src.type)+' '+src.uuid,scene);m.albedoColor=src.color?new B.Color3(src.color.r,src.color.g,src.color.b):B.Color3.White();m.metallic=src.metalness||0;m.roughness=src.roughness??.82;m.alpha=src.opacity??1;m.backFaceCulling=src.side!==T.DoubleSide;m.twoSidedLighting=!m.backFaceCulling;m.unlit=!!src.isMeshBasicMaterial;m.environmentIntensity=kind==='metal'?1:.7;m.metadata={kind};if(src.map)m.albedoTexture=texture(src.map);if(src.transparent&&m.albedoTexture){m.albedoTexture.hasAlpha=true;m.useAlphaFromAlbedoTexture=true;}if(src.bumpMap){m.bumpTexture=texture(src.bumpMap,true);m.bumpTexture.level=kind==='roof'?.55:.2;}if(src.emissive){m.emissiveColor=new B.Color3(src.emissive.r,src.emissive.g,src.emissive.b).scale(src.emissiveIntensity||0);m.metadata.emissiveBase=m.emissiveColor.clone();}if(src.transparent){m.transparencyMode=B.PBRMaterial.PBRMATERIAL_ALPHABLEND;m.disableDepthWrite=src.depthWrite===false;}if(src.clearcoat){m.clearCoat.isEnabled=true;m.clearCoat.intensity=src.clearcoat;m.clearCoat.roughness=src.clearcoatRoughness||.2;}if(kind==='water'){m.albedoColor=color('#388f9b').toLinearSpace();m.metallic=.1;m.roughness=.12;m.alpha=.86;m.clearCoat.isEnabled=true;m.clearCoat.intensity=.9;m.clearCoat.roughness=.1;m.bumpTexture=waterNormal;m.bumpTexture.level=.3;m.environmentIntensity=1;m.subSurface.indexOfRefraction=1.333;}materialCache.set(src.uuid,m);return m;}
function geometry(src){if(geometryCache.has(src.uuid))return geometryCache.get(src.uuid);const v=new B.VertexData(),position=src.attributes.position;v.positions=new Float32Array(position.array);if(src.attributes.normal)v.normals=new Float32Array(src.attributes.normal.array);if(src.attributes.uv)v.uvs=new Float32Array(src.attributes.uv.array);if(src.attributes.color)v.colors=new Float32Array(src.attributes.color.array);v.indices=src.index?new Uint32Array(src.index.array):Uint32Array.from({length:position.count},(_,i)=>i);if(!v.normals){const ns=[];B.VertexData.ComputeNormals(v.positions,v.indices,ns,{useRightHandedSystem:true});v.normals=ns;}const g=new B.Geometry('Author mesh '+src.uuid,scene,v,false);geometryCache.set(src.uuid,g);return g;}
function bind(source,node){const p=source.position,s=source.scale,q=source.quaternion;if(!node.position.equalsToFloats(p.x,p.y,p.z))node.position.copyFromFloats(p.x,p.y,p.z);if(!node.scaling.equalsToFloats(s.x,s.y,s.z))node.scaling.copyFromFloats(s.x,s.y,s.z);if(!node.rotationQuaternion)node.rotationQuaternion=B.Quaternion.Identity();if(!node.rotationQuaternion.equalsToFloats(q.x,q.y,q.z,q.w))node.rotationQuaternion.copyFromFloats(q.x,q.y,q.z,q.w);node.setEnabled(source.visible);}
function imported(key,parent,width,depth,height,owner,offsetX=0,bare=false){const asset=containers.get(key);if(!asset)return false;const fit=new B.TransformNode('Imported '+key,scene);const parts=asset.instantiateModelsToScene(n=>'Imported '+key+' '+n,false,{doNotInstantiate:false,predicate:n=>!bare||(!n.name.includes('ceramic pot')&&!n.name.includes('Soil'))});for(const root of parts.rootNodes){root.parent=fit;root.setEnabled(true);}fit.computeWorldMatrix(true);const bounds=fit.getHierarchyBoundingVectors(true,m=>m.getTotalVertices()>0),size=bounds.max.subtract(bounds.min),scale=height?(key==='trees'||key==='pines'?Math.min(height/size.y,2.1/size.x,2.1/size.z):height/size.y):Math.min((width-.08)/Math.max(size.x,.01),(depth-.06)/Math.max(size.z,.01));fit.scaling.setAll(scale);fit.position.set(offsetX+width/2-(bounds.min.x+size.x/2)*scale,-bounds.min.y*scale,depth/2-(bounds.min.z+size.z/2)*scale);fit.parent=parent;fit.metadata={importedAsset:key};for(const mesh of fit.getChildMeshes()){mesh.isPickable=!!owner;mesh.metadata={assetId:owner?.id,importedAsset:key};if(mesh.sourceMesh)mesh.sourceMesh.receiveShadows=true;else mesh.receiveShadows=true;if(mesh.getTotalVertices()>0)shadows.addShadowCaster(mesh,false);}importInstances++;return true;}
let roofTileGeometry=null;const tileMaterials=new Map();
function tileGeometry(){if(roofTileGeometry)return roofTileGeometry;const pos=[],uv=[],indices=[];for(let end=0;end<2;end++)for(let j=0;j<=8;j++){let t=j*Math.PI/8;pos.push(end?.145:-.145,Math.sin(t)*.043,Math.cos(t)*.091);uv.push(end,j/8);}for(let j=0;j<8;j++){indices.push(j,j+1,j+9,j+1,j+10,j+9);}const normals=[];B.VertexData.ComputeNormals(pos,indices,normals,{useRightHandedSystem:true});const vd=new B.VertexData();vd.positions=pos;vd.normals=normals;vd.uvs=uv;vd.indices=indices;return roofTileGeometry=new B.Geometry('Curved fired-clay roof tile',scene,vd,false);}
function roofTiles(source,parent){if(source.geometry?.type!=='BufferGeometry'||source.material?.userData.kind!=='roof'||source.geometry.attributes.position.count!==10)return;const p=source.geometry.attributes.position.array,profile=[];for(let i=0;i<p.length;i+=6)profile.push({x:p[i],y:p[i+1]});let minX=profile[0].x,maxX=profile.at(-1).x,z0=p[2],z1=p[5];const nx=Math.max(1,Math.floor((maxX-minX)/.24)),nz=Math.max(1,Math.floor((z1-z0)/.18)),matrices=new Float32Array(nx*nz*16),colors=new Float32Array(nx*nz*4);let count=0;
 for(let i=0;i<nx;i++){const x=minX+(i+.5)*(maxX-minX)/nx;let left=profile[0],right=profile[1];for(let j=0;j<profile.length-1;j++)if(x>=profile[j].x&&x<=profile[j+1].x){left=profile[j];right=profile[j+1];break;}const slope=(right.y-left.y)/(right.x-left.x),y=left.y+(x-left.x)*slope+.016,rotation=B.Quaternion.RotationAxis(B.Axis.Z,Math.atan(slope));for(let j=0;j<nz;j++){const z=z0+(j+.5)*(z1-z0)/nz;B.Matrix.Compose(new B.Vector3(1,1,1),rotation,new B.Vector3(x,y,z)).copyToArray(matrices,count*16);const shade=.94+((i*7+j*11)%13)*.009;colors.set([shade,shade,shade,1],count*4);count++;}}
 const mesh=new B.Mesh('Individual curved roof tiles',scene);mesh.sideOrientation=B.Material.CounterClockWiseSideOrientation;tileGeometry().copy('Roof patch '+B.Tools.RandomId()).applyToMesh(mesh);mesh.parent=parent;const key=source.material.color.getHexString();if(!tileMaterials.has(key)){const m=new B.PBRMaterial('Fired clay '+key,scene);m.albedoColor=color('#'+key).toLinearSpace();m.roughness=.78;m.metallic=0;m.backFaceCulling=false;m.twoSidedLighting=true;tileMaterials.set(key,m);}mesh.material=tileMaterials.get(key);mesh.thinInstanceSetBuffer('matrix',matrices,16,true);mesh.thinInstanceSetBuffer('color',colors,4,true);mesh.thinInstanceRefreshBoundingInfo(true);mesh.isPickable=parent.isPickable;mesh.metadata={assetId:parent.metadata?.assetId,roofTiles:true};if(mesh.sourceMesh)mesh.sourceMesh.receiveShadows=true;else mesh.receiveShadows=true;shadows.addShadowCaster(mesh,false);
}
function make(source,parent=null,owner=null,ghostMaterial=null){let node;
 if(source.isMesh){node=new B.Mesh(source.name||'Spa mesh',scene);node.sideOrientation=B.Material.CounterClockWiseSideOrientation;const baseGeometry=geometry(source.geometry);(source.isInstancedMesh?baseGeometry.copy('Batch '+B.Tools.RandomId()):baseGeometry).applyToMesh(node);node.material=ghostMaterial||material(source.material);node.receiveShadows=source.receiveShadow!==false;node.isPickable=!!owner;if(source.castShadow!==false&&!ghostMaterial)shadows.addShadowCaster(node,false);if(source.isInstancedMesh){node.thinInstanceSetBuffer('matrix',new Float32Array(source.instanceMatrix.array),16,false);node.thinInstanceCount=source.count;if(source.instanceColor){const colors=new Float32Array(source.count*4);for(let i=0;i<source.count;i++)colors.set([...source.instanceColor.array.subarray(i*3,i*3+3),1],i*4);node.thinInstanceSetBuffer('color',colors,4,true);}node.thinInstanceRefreshBoundingInfo(true);}}
 else node=new B.TransformNode(source.name||'Spa group',scene);
 node.parent=parent;node.metadata={source,assetId:owner?.id,instanceVersion:source.instanceMatrix?.version};bind(source,node);records.add(node);
 const asset=source.userData?.asset;
 if(!ghostMaterial&&ready&&asset==='plant'&&imported('olive',node,1,1,1.9,owner))return node;
 if(!ghostMaterial&&ready&&asset==='palm'&&imported('palm',node,1,1,1.9,owner))return node;
 if(!ghostMaterial&&ready&&asset==='sofa'&&imported('sofa',node,byId.sofa.w,byId.sofa.d,null,owner))return node;
 if(!ghostMaterial&&ready&&asset==='pinksofa'){imported('chair',node,1,1,null,owner,0);imported('chair',node,1,1,null,owner,1);return node;}
 if(!ghostMaterial&&ready&&source.userData.artSway!==undefined){const key=Math.floor(source.userData.artSway*10)%5===0?'pines':'olive';if(imported(key,node,1.8,1.8,source.userData.artHeight||2.65,owner,0,key==='olive'))return node;}
 for(const child of source.children)make(child,node,owner,ghostMaterial);
 if(source.userData.roofSide&&!ghostMaterial)roofTiles(source,node);
 return node;
}
function sync(node){const src=node.metadata?.source;if(!src)return;bind(src,node);if(src.isInstancedMesh&&node.metadata.instanceVersion!==src.instanceMatrix.version){node.metadata.instanceVersion=src.instanceMatrix.version;node.thinInstanceSetBuffer('matrix',new Float32Array(src.instanceMatrix.array),16,false);node.thinInstanceCount=src.count;node.thinInstanceRefreshBoundingInfo(true);}}
function dispose(node){if(!node)return;const children=[node,...node.getDescendants()];for(const n of children){records.delete(n);if(n instanceof B.AbstractMesh)shadows.removeShadowCaster(n,false);}node.dispose(false,false);for(const [id,g] of geometryCache)if(!g.meshes.length){g.dispose();geometryCache.delete(id);}markShadows();}
function updateView(){const [cx,cy]=center();view.orthoLeft=(-cx-camera.x)/camera.zoom;view.orthoRight=(W-cx-camera.x)/camera.zoom;view.orthoTop=(cy+camera.y)/camera.zoom;view.orthoBottom=-(H-cy-camera.y)/camera.zoom;view.position.set(Math.sin(camera.angle)*camera.tilt*worldDistance,Math.sqrt(1-camera.tilt**2)*worldDistance,Math.cos(camera.angle)*camera.tilt*worldDistance);view.setTarget(B.Vector3.Zero());view.maxZ=worldDistance*2+1000;view.getViewMatrix(true);view.getProjectionMatrix(true);scene.setTransformMatrix(view.getViewMatrix(),view.getProjectionMatrix());}
project=(x,y,z=0)=>{updateView();const p=B.Vector3.Project(new B.Vector3(x,z,y),B.Matrix.Identity(),scene.getTransformMatrix(),new B.Viewport(0,0,W,H));return [p.x,p.y]};
unproject=(px,py)=>{updateView();const ray=scene.createPickingRay(px,py,B.Matrix.Identity(),view,false);if(tool==='inspect'||tool==='remove'){const hit=scene.pickWithRay(ray,m=>m.isEnabled()&&m.isVisible&&!!m.metadata?.assetId);if(hit?.hit){const o=objects.find(o=>o.id===hit.pickedMesh.metadata.assetId);if(o)return {x:o.x,y:o.y};}}const d=ray.intersectsPlane(new B.Plane(0,1,0,0));if(d===null)return {x:0,y:0};const hit=ray.origin.add(ray.direction.scale(d));return {x:Math.floor(hit.x+1e-7),y:Math.floor(hit.z+1e-7)};};
const ocean=B.MeshBuilder.CreateGround('Reflective lagoon',{width:20000,height:20000},scene);ocean.position.y=-.72;ocean.isPickable=false;const oceanMat=new B.PBRMaterial('Lagoon water',scene);ocean.material=oceanMat;oceanMat.albedoColor=color('#5398a6');oceanMat.metallic=.16;oceanMat.roughness=.2;oceanMat.clearCoat.isEnabled=true;oceanMat.clearCoat.intensity=1;oceanMat.clearCoat.roughness=.15;const oceanWaves=waterNormal.clone();oceanWaves.name='Lagoon wave normals';oceanWaves.uScale=oceanWaves.vScale=2000;oceanMat.bumpTexture=oceanWaves;oceanMat.bumpTexture.level=.35;oceanMat.environmentIntensity=1;
let mirror=new B.MirrorTexture('Lagoon reflects the resort',512,scene,true);mirror.mirrorPlane=new B.Plane(0,-1,0,-.72);mirror.level=.35;mirror.blurKernel=10;mirror.refreshRate=3;oceanMat.reflectionTexture=mirror;
function reflectList(){mirror.renderList=scene.meshes.filter(m=>m!==ocean&&!m.metadata?.source?.userData.ripple&&m.isEnabled()&&m.material&&m.material.alpha>=.9&&m.getTotalVertices()>0);mirror.resetRefreshCounter();}
function updateFloors(){const stamp=[...floors].map(([k,v])=>k+':'+v).join('|')+':'+assetRevision;if(stamp===floorStamp)return;floorStamp=stamp;revision++;dispose(landscape);dispose(floorWorld);floorSources.clear();library.art.update(floors);landscape=make(library.art.root);const wood=[],stone=[];for(const [k,type]of floors){const [x,z]=k.split(',').map(Number);(type==='lobby'?wood:stone).push([x,z]);}
 for(const [tiles,col,kind]of [[wood,'#cab18d','wood'],[stone,'#dbd9cb','stone']]){if(!tiles.length)continue;const mesh=new T.InstancedMesh(library.geom('floor',()=>new T.BoxGeometry(.993,.18,.993)),library.mat(col,kind),tiles.length);mesh.receiveShadow=true;mesh.castShadow=false;tiles.forEach(([x,z],i)=>{scratch.position.set(x+.5,-.09,z+.5);scratch.rotation.set(0,0,0);scratch.scale.setScalar(1);scratch.updateMatrix();mesh.setMatrixAt(i,scratch.matrix);mesh.setColorAt(i,new T.Color('#ffffff').multiplyScalar(.95+i%7*.01));});floorSources.add(mesh);}
 floorWorld=make(floorSources);let minX=Infinity,maxX=-Infinity,minZ=Infinity,maxZ=-Infinity;for(const k of floors.keys()){const [x,z]=k.split(',').map(Number);minX=Math.min(minX,x);maxX=Math.max(maxX,x+1);minZ=Math.min(minZ,z);maxZ=Math.max(maxZ,z+1);}const span=Math.max(maxX-minX,maxZ-minZ,24);worldDistance=150+Math.hypot(Math.max(Math.abs(minX),Math.abs(maxX)),Math.max(Math.abs(minZ),Math.abs(maxZ)));sun.position.set((minX+maxX)/2-13,22+span*.2,(minZ+maxZ)/2+11);markShadows();reflectList();}
const steamSystems=new Map();
const steamTexture=new B.DynamicTexture('Soft steam',{width:128,height:128},scene,false);const steamContext=steamTexture.getContext(),steamGradient=steamContext.createRadialGradient(64,64,0,64,64,64);steamGradient.addColorStop(0,'rgba(255,252,240,.85)');steamGradient.addColorStop(.4,'rgba(255,252,240,.35)');steamGradient.addColorStop(1,'rgba(255,252,240,0)');steamContext.fillStyle=steamGradient;steamContext.fillRect(0,0,128,128);steamTexture.hasAlpha=true;steamTexture.update();
function attachSteam(node,o){const a=byId[o.type],system=new B.ParticleSystem('Warm steam '+o.id,64,scene);system.particleTexture=steamTexture;system.emitter=node;system.createBoxEmitter(new B.Vector3(-.1,.4,-.1),new B.Vector3(.1,.8,.1),new B.Vector3(a.w*.3,.7,a.d*.3),new B.Vector3(a.w*.7,.8,a.d*.7));system.minLifeTime=2;system.maxLifeTime=3.8;system.minSize=.35;system.maxSize=.7;system.emitRate=10;system.minEmitPower=.25;system.maxEmitPower=.5;system.gravity=new B.Vector3(0,.03,0);system.color1=new B.Color4(1,.98,.94,.14);system.color2=new B.Color4(1,1,1,.1);system.colorDead=new B.Color4(1,1,1,0);system.blendMode=B.ParticleSystem.BLENDMODE_STANDARD;system.addSizeGradient(0,.4);system.addSizeGradient(1,1.8);if(quality!=='simple')system.start();steamSystems.set(o.id,system);}
function updateObjects(){const stamp=objects.map(o=>o.id+':'+o.type+':'+o.x+':'+o.y+':'+o.r).join('|')+':'+assetRevision;if(stamp===objectStamp)return;objectStamp=stamp;revision++;const ids=new Set(objects.map(o=>o.id));for(const [id,node]of objectModels)if(!ids.has(id)||node.metadata.revision!==assetRevision||objects.find(o=>o.id===id)?.type!==node.metadata.assetType){steamSystems.get(id)?.dispose(false);steamSystems.delete(id);dispose(node);objectModels.delete(id);const src=sourceObjects.get(id);src?.removeFromParent();sourceObjects.delete(id);}for(const o of objects){let node=objectModels.get(o.id),source=sourceObjects.get(o.id);if(!node){source=library.model(o.type);source.userData.id=o.id;sourceObjects.set(o.id,source);objectSources.add(source);library.placeModel(source,o);node=make(source,null,o);node.metadata.revision=assetRevision;node.metadata.assetType=o.type;objectModels.set(o.id,node);if(source.userData.steam)attachSteam(node,o);}else library.placeModel(source,o);}markShadows();reflectList();}
  function updateGuests(){const ids=new Set(people.map(p=>p.id));for(let [id,g] of guestMeshes)if(!ids.has(id)){guestRoot.remove(g);guestMeshes.delete(id)}for(let p of people){let g=guestMeshes.get(p.id);if(!g){g=library.guestModel(p);guestMeshes.set(p.id,g);guestRoot.add(g);g.visible=false;}let o=objects.find(o=>o.id===p.target),a=o&&byId[o.type],using=p.state==='using',bathing=using&&a&&['tub','pool','bath'].includes(a.kind),seated=using&&a&&['sofa','lounger','quiet'].includes(a.kind);let px=p.x,pz=p.y,py=0;
      if(using&&o){const others=people.filter(v=>v.target===o.id&&v.state==='using'),i=others.findIndex(v=>v.id===p.id),[w,d]=dimensions(o);if(bathing){let theta=i*2.399;px=o.x+w/2+Math.cos(theta)*Math.min(w,d)*.17;pz=o.y+d/2+Math.sin(theta)*Math.min(w,d)*.17;py=.24;}else if(seated){px=o.x+w/2+(i-.5)*.45;pz=o.y+d*.6;py=.15;}}
      g.position.set(px,py,pz);const body=g.userData.body;body.position.y=p.state==='walking'?Math.sin(p.phase*2)*.018:Math.sin(elapsed*1.5+p.id*7)*.004;
      if(p.path.length){let next=p.path[0];g.rotation.y=Math.atan2(next.x-p.x,next.y-p.y)}else if(using)g.rotation.y=0;
      for(let {leg,arm,side} of g.userData.limbs){leg.visible=!bathing;leg.rotation.x=seated?-1.2:p.state==='walking'?Math.sin(p.phase)*.43*side:0;arm.rotation.x=p.state==='walking'?-Math.sin(p.phase)*.28*side:bathing?-.7:seated?-.3:0;arm.rotation.z=bathing?side*.6:side*.08;}
    }
    // Guest skeletons stay lightweight and hidden; their posed parts draw in shared batches.
    const parts=new Map();for(let g of guestMeshes.values()){g.updateMatrixWorld(true);g.traverse(m=>{if(!m.isMesh||!m.visible)return;let parent=m.parent;while(parent&&parent!==g){if(!parent.visible)return;parent=parent.parent}const key=m.geometry.uuid+':'+m.material.uuid;if(!parts.has(key))parts.set(key,[]);parts.get(key).push(m)})}
    for(let [key,batch] of guestBatches){if(!parts.has(key)){batch.count=0;batch.visible=false}}
    for(let [key,nodes] of parts){let batch=guestBatches.get(key);if(!batch){batch=new T.InstancedMesh(nodes[0].geometry,nodes[0].material,84);batch.instanceMatrix.setUsage(T.DynamicDrawUsage);batch.castShadow=false;batch.receiveShadow=true;batch.frustumCulled=false;guestBatchRoot.add(batch);guestBatches.set(key,batch)}batch.count=nodes.length;batch.visible=true;nodes.forEach((node,i)=>batch.setMatrixAt(i,node.matrixWorld));batch.instanceMatrix.needsUpdate=true;}
  }

function updateGuestNodes(){for(const [id,source]of guestBatches){if(!guestNodes.has(id))guestNodes.set(id,make(source));}}
const goodGhost=new B.StandardMaterial('Valid placement',scene);goodGhost.diffuseColor=color('#a6c389');goodGhost.alpha=.38;goodGhost.backFaceCulling=false;goodGhost.disableDepthWrite=true;const badGhost=goodGhost.clone('Invalid placement');badGhost.diffuseColor=color('#c69282');
function updateIndicator(){const stamp=(hover?tool+':'+selectedAsset+':'+turn+':'+hover.x+':'+hover.y:'none')+':'+selected+':'+revision;if(stamp===indicatorStamp)return;indicatorStamp=stamp;dispose(indicator);dispose(ghost);indicator=null;ghost=null;let cell=hover,w=1,d=1,valid=true;if(tool==='inspect'&&selected){const o=objects.find(o=>o.id===selected);if(o){cell={x:o.x,y:o.y};[w,d]=dimensions(o);}}else if(!hover||!['floor','build','remove'].includes(tool))return;if(!cell)return;if(tool==='build'){const a=byId[selectedAsset];[w,d]=turn%2?[a.d,a.w]:[a.w,a.d];valid=canPlace({type:selectedAsset,x:cell.x,y:cell.y,r:turn});const source=library.model(selectedAsset);library.placeModel(source,{type:selectedAsset,x:cell.x,y:cell.y,r:turn});ghost=make(source,null,null,valid?goodGhost:badGhost);}const points=[[cell.x,.045,cell.y],[cell.x+w,.045,cell.y],[cell.x+w,.045,cell.y+d],[cell.x,.045,cell.y+d],[cell.x,.045,cell.y]].map(p=>new B.Vector3(...p));indicator=B.MeshBuilder.CreateLines('Selected tile footprint',{points},scene);indicator.color=color(tool==='remove'?'#ab685a':valid?'#577544':'#b96759');indicator.isPickable=false;}
const lampLights=Array.from({length:8},()=>{const l=new B.PointLight('Paper lantern',new B.Vector3(0,1.2,0),scene);l.diffuse=color('#ffc57f');l.intensity=0;l.range=5;return l;});
function remember(){try{localStorage.setItem('stillwater-visuals',JSON.stringify({theme,quality,roofMode,engine:'Babylon.js'}));}catch{}}
function setTheme(mode){if(!['morning','golden','evening'].includes(mode))return;theme=mode;const p={morning:{sun:'#fff1d9',power:1.8,environment:.65,exposure:1.05,water:'#569dab'},golden:{sun:'#ffd1a3',power:2.0,environment:.5,exposure:1.05,water:'#60959e'},evening:{sun:'#b4d7ff',power:.5,environment:.32,exposure:1.3,water:'#315d7e'}}[mode];sun.diffuse=color(p.sun);sun.intensity=p.power;scene.environmentIntensity=p.environment;scene.imageProcessingConfiguration.exposure=p.exposure;scene.imageProcessingConfiguration.contrast=1.12;oceanMat.albedoColor=color(p.water).toLinearSpace();for(const m of materialCache.values())if(m.metadata.emissiveBase)m.emissiveColor=m.metadata.emissiveBase.scale(mode==='evening'?5:1);if($('lightMode'))$('lightMode').textContent=mode==='morning'?'☀ Morning':mode==='golden'?'☀ Golden hour':'☾ Evening';markShadows();remember();}
function setRoofs(mode){if(!['cutaway','full','none'].includes(mode))return;roofMode=mode;library.art.setRoofMode(mode);if($('roofMode'))$('roofMode').textContent=mode==='full'?'▱ Buildings':mode==='none'?'▱ Open sky':'▱ Cutaway';markShadows();remember();}
function cycleRoofs(){setRoofs(roofMode==='cutaway'?'full':roofMode==='full'?'none':'cutaway');}
function setQuality(mode){if(!['balanced','lush','simple'].includes(mode))return;quality=mode;for(const system of steamSystems.values()){if(mode==='simple')system.stop();else system.start();}if(ssao){ssao.dispose();ssao=null;}if(pipeline){pipeline.dispose();pipeline=null;}pipeline=new B.DefaultRenderingPipeline('Spa film and anti-aliasing',true,scene,[view]);pipeline.fxaaEnabled=true;pipeline.samples=mode==='lush'?4:mode==='balanced'?2:1;pipeline.bloomEnabled=mode!=='simple';pipeline.bloomThreshold=1.4;pipeline.bloomWeight=.08;pipeline.bloomKernel=24;scene.imageProcessingConfiguration.toneMappingEnabled=true;scene.imageProcessingConfiguration.toneMappingType=B.ImageProcessingConfiguration.TONEMAPPING_ACES;scene.shadowsEnabled=mode!=='simple';shadows.getShadowMap().resize(mode==='lush'?4096:2048);mirror.refreshRate=mode==='lush'?2:4;mirror.renderList=mode==='simple'?[]:scene.meshes.filter(m=>m!==ocean&&m.isEnabled()&&m.material?.alpha>=.9);oceanMat.reflectionTexture=mode==='simple'?null:mirror;if(mode!=='simple'&&B.SSAO2RenderingPipeline.IsSupported){ssao=new B.SSAO2RenderingPipeline('Architectural contact shading',scene,{ssaoRatio:mode==='lush'?.75:.5,blurRatio:1},[view]);ssao.totalStrength=mode==='lush'?1.1:.75;ssao.radius=.85;ssao.samples=mode==='lush'?16:8;ssao.maxZ=50000;ssao.expensiveBlur=true;ssao.bilateralSamples=8;ssao.bilateralSoften=.2;}sizedW=0;markShadows();remember();}
function fit(){const ratio=Math.min(devicePixelRatio||1,quality==='lush'?2:quality==='simple'?1:1.5);engine.setHardwareScalingLevel(1/ratio);engine.setSize(Math.round(W*ratio),Math.round(H*ratio),true);sizedW=W;sizedH=H;}
function animateSources(){for(const g of sourceObjects.values()){g.traverse(m=>{if(m.userData.cutaway){const angle=camera.angle-g.rotation.y,front=m.userData.cutaway==='back'?Math.cos(angle)<-.12:Math.sin(angle)<-.12,scale=roofMode!=='full'&&front?.27:1;if(m.scale.y!==scale){m.scale.y=scale;m.position.y=.12+1.7*scale/2;markShadows();}}if(m.userData.ripple){const t=(elapsed*.18+m.userData.ripple.phase)%1;m.scale.set(1+t*1.2,1+t*1.2,1);m.material.opacity=(1-t)*.2;}if(m.userData.sway)m.rotation.z=Math.sin(elapsed*.6+g.position.x)*.009;});}library.art.animate(camera.angle,sourceObjects.values(),elapsed,tool==='build'||tool==='floor');if(library.renderer?.shadowMap.needsUpdate){markShadows();library.renderer.shadowMap.needsUpdate=false;}waterNormal.uOffset=elapsed*.003;waterNormal.vOffset=elapsed*.002;oceanWaves.uOffset=elapsed*.008;oceanWaves.vOffset=elapsed*.005;const lamps=objects.filter(o=>o.type==='lantern').slice(0,8);lampLights.forEach((l,i)=>{l.intensity=lamps[i]?(theme==='evening'?2.8:.05):0;if(lamps[i])l.position.set(lamps[i].x+.5,1.2,lamps[i].y+.5);});}
const thumbnailCache=new Map();let thumbnailBusy=false,thumbnailPending=false;
async function renderCatalogThumbnails(){if(!ready)return;if(thumbnailBusy){thumbnailPending=true;return;}thumbnailBusy=true;try{for(const el of document.querySelectorAll('[data-thumb]')){const id=el.dataset.thumb;if(!thumbnailCache.has(id)){const source=library.model(id),root=make(source),meshes=root.getChildMeshes();root.position.set(0,0,0);for(const mesh of meshes){mesh.layerMask=0x10000000;shadows.removeShadowCaster(mesh,false);}root.computeWorldMatrix(true);const b=root.getHierarchyBoundingVectors(true),center=b.min.add(b.max).scale(.5),size=b.max.subtract(b.min),extent=Math.max(Math.max(size.x,size.z)*.65+size.y*.6,1.7);const camera=new B.UniversalCamera('Catalog camera',center.add(new B.Vector3(-5,5,7)),scene);camera.setTarget(center);camera.layerMask=0x10000000;camera.mode=B.Camera.ORTHOGRAPHIC_CAMERA;camera.orthoLeft=-extent;camera.orthoRight=extent;camera.orthoTop=extent*.566;camera.orthoBottom=-extent*.566;const target=new B.RenderTargetTexture('Catalog preview',{width:240,height:136},scene,false,true);target.activeCamera=camera;target.renderList=meshes;target.clearColor=new B.Color4(.92,.94,.9,1);target.ignoreCameraViewport=true;await Promise.all(meshes.filter(m=>m.material&&m.getTotalVertices()>0).map(m=>m.material.forceCompilationAsync(m)));target.render();const pixels=await target.readPixels();if(pixels){const c=document.createElement('canvas');c.width=240;c.height=136;const context=c.getContext('2d'),image=context.createImageData(240,136);for(let y=0;y<136;y++)image.data.set(pixels.subarray((135-y)*240*4,(136-y)*240*4),y*240*4);context.putImageData(image,0,0);thumbnailCache.set(id,c);}target.dispose();camera.dispose();dispose(root);}const img=thumbnailCache.get(id);if(img&&el.isConnected)el.getContext('2d').drawImage(img,0,0);} }catch(error){console.error('Catalog render failed',error);}finally{thumbnailBusy=false;if(thumbnailPending){thumbnailPending=false;renderCatalogThumbnails();}}}
renderThumbs=()=>{renderCatalogThumbnails();};
draw=(force=false)=>{const now=performance.now();if(!force&&now-lastDraw<1000/(settled?30:3))return;lastDraw=now;elapsed=now/1000;if(sizedW!==W||sizedH!==H)fit();updateFloors();updateObjects();updateGuests();updateGuestNodes();updateIndicator();animateSources();for(const node of records)sync(node);updateView();engine._drawCalls.fetchNewFrame();engine.beginFrame();scene.render();engine.endFrame();};
const lightButton=document.createElement('button');lightButton.id='lightMode';lightButton.className='plain hide-small';lightButton.title='Change the light in your sanctuary';lightButton.onclick=()=>setTheme(theme==='morning'?'golden':theme==='golden'?'evening':'morning');document.querySelector('.actions').prepend(lightButton);
const roofButton=document.createElement('button');roofButton.id='roofMode';roofButton.className='plain hide-small';roofButton.title='Show buildings or cut away roofs · C';roofButton.onclick=cycleRoofs;document.querySelector('.actions').prepend(roofButton);
window.addEventListener('keydown',e=>{if(e.target.tagName==='INPUT')return;if(e.key.toLowerCase()==='c')cycleRoofs();if(e.key.toLowerCase()==='p')document.body.classList.toggle('photo-mode');});
const originalMenu=menu;menu=()=>{originalMenu();const p=document.createElement('p');p.innerHTML='<b>Make it yours</b><br><button class="secondary" id="detailMode"></button><button class="secondary" id="menuLight"></button><button class="secondary" id="cutaway"></button><button class="secondary" id="photoView">Photo view</button><button class="secondary" id="assetCredits">Credits</button><br><span style="font-size:10px">C changes roofs · P opens photo view. Lush adds finer shadows and contact shading; Simple suits older devices.</span>';$('modal').insertBefore(p,$('modal').lastElementChild);const labels=()=>{$('detailMode').textContent=quality==='lush'?'Lush':quality==='simple'?'Simple':'Balanced';$('menuLight').textContent=theme==='morning'?'Morning':theme==='golden'?'Golden hour':'Evening';$('cutaway').textContent=roofMode==='full'?'Whole buildings':roofMode==='none'?'Open sky':'Cutaway';};labels();$('detailMode').onclick=()=>{setQuality(quality==='balanced'?'lush':quality==='lush'?'simple':'balanced');labels();};$('menuLight').onclick=()=>{setTheme(theme==='morning'?'golden':theme==='golden'?'evening':'morning');labels();};$('cutaway').onclick=()=>{cycleRoofs();labels();};$('photoView').onclick=()=>{document.body.classList.add('photo-mode');$('modalback').style.display='none';};$('assetCredits').onclick=()=>{$('modal').innerHTML='<h2>Craft & credits</h2><p>Rendered with Babylon.js '+B.Engine.Version+' (Apache 2.0). glTF imports preserve authored geometry, textures, normals, and fabric sheen.</p><p><b>Sheen Chair:</b> Eric Chadwick / Wayfair, 2020, CC0.<br><b>Sheen Wood Leather Sofa:</b> original Fran Calvente, 2021 (CC0); improvements Eric Chadwick / Darmstadt Graphics Group, 2024 (<a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">CC BY 4.0</a>). Models are fitted to the game’s building grid. <a href="https://github.com/KhronosGroup/glTF-Sample-Assets" target="_blank" rel="noreferrer">Original model sources</a>.<br><b>Garden trees:</b> Kenney, CC0.<br><b>Potsdamer Platz light:</b> HDRI Haven / Poly Haven, CC0.<br>Modular spa geometry uses Three.js (MIT) as an authoring helper. Rendering and effects use Babylon.js.</p><button id="creditBack">Back</button>';$('creditBack').onclick=menu;};};$('menu').onclick=menu;
engine.onContextLostObservable.add(()=>{paused=true;toast('Graphics paused. Save your spa, then refresh to restore the view.');updateUI();});
window.spaGraphics={mode:'webgl',engine:'Babylon.js',version:B.Engine.Version,get ready(){return ready&&settled},get quality(){return quality},get theme(){return theme},catalogReady:()=>Array.from(document.querySelectorAll('[data-thumb]')).every(e=>thumbnailCache.has(e.dataset.thumb)),setTheme,setQuality,setRoofMode:setRoofs,scene,sourceScene,artStats:()=>library.art.stats(),postStats:()=>({depthShading:!!ssao,antialiasSamples:pipeline?.samples||1,reflection:quality!=='simple',engine:'Babylon.js'}),stats:()=>({calls:engine._drawCalls?.current||0,triangles:scene.getActiveIndices()/3,geometries:scene.geometries.length,textures:scene.textures.length,guestDrawCalls:[...guestNodes.values()].filter(n=>n.isEnabled()&&n.thinInstanceCount>0).length,importedAssets:containers.size,importedInstances:importInstances,engine:'Babylon.js'}),testModels:()=>{for(const a of assets){const source=library.model(a.id);for(let r=0;r<4;r++){library.placeModel(source,{type:a.id,x:0,y:0,r});source.updateMatrixWorld();const b=new T.Box3().setFromObject(source);if(!Number.isFinite(b.max.x+b.max.y+b.max.z))throw Error('Invalid model: '+a.id);}}return assets.length;}};
let saved;try{saved=JSON.parse(localStorage.getItem('stillwater-visuals'));}catch{}if(saved){if(['morning','golden','evening'].includes(saved.theme))theme=saved.theme;if(['balanced','lush','simple'].includes(saved.quality))quality=saved.quality;if(['cutaway','full','none'].includes(saved.roofMode))roofMode=saved.roofMode;}setRoofs(roofMode);setTheme(theme);setQuality(quality);fit();draw(true);
(async()=>{try{
 const models=Object.keys(STILLWATER_ASSETS).filter(k=>k!=='hdr');for(const key of models){const container=await B.LoadAssetContainerAsync(bytes(key),scene,{pluginExtension:'.glb',name:STILLWATER_ASSETS[key].name});containers.set(key,container);}
 const env=await new Promise((resolve,reject)=>{let texture;texture=new B.HDRCubeTexture('data:application/octet-stream;base64,'+STILLWATER_ASSETS.hdr.data,scene,128,false,true,false,false,()=>resolve(texture),(message,error)=>reject(error||Error(message)));});scene.environmentTexture=env;
 ready=true;assetRevision++;floorStamp='';objectStamp='';draw(true);await scene.whenReadyAsync();await shadows.forceCompilationAsync({useInstances:true});settled=true;markShadows();mirror.resetRefreshCounter();for(let i=0;i<2;i++)draw(true);renderCatalogThumbnails();
 }catch(error){console.error('Local engine assets failed to load',error);ready=true;settled=true;toast('Some detailed assets could not load. The spa remains playable.');}
})();
})();
