"""Author the matching spa fixture kit in Blender. No geometry is generated by the browser.

KayKit's gradient-textured, soft low-poly furniture is the art reference. Beveled
edges, restrained gradients, uniform texel-free materials and shared proportions
keep these spa-specific additions in the same visual language.
Run: blender --background --python tools/bake-spa.py
"""
import bpy, math, random
from pathlib import Path
from mathutils import Vector

OUT = Path(__file__).resolve().parents[1] / 'godot/assets/spa'
OUT.mkdir(parents=True, exist_ok=True)
random.seed(18)
PALETTE = {'cream':'E4D9BD','stone':'C8C5AF','edge':'ADA995','wood':'AF805D',
           'darkwood':'735547','cedar':'C49872','sage':'8DAB95','teal':'528F89',
           'clay':'C48972','linen':'E9DFCA','gold':'BDA272','leaf':'739477',
           'grass':'A1B39A','earth':'9B927F','charcoal':'465D55','water':'79B8AD'}
materials={}
for name,h in PALETTE.items():
    m=bpy.data.materials.new(name);m.use_nodes=True
    col=[int(h[i:i+2],16)/255 for i in (0,2,4)]
    # Blender takes linear material colors; convert the deliberately chosen sRGB palette.
    linear=[((v+.055)/1.055)**2.4 if v>.04045 else v/12.92 for v in col]
    p=m.node_tree.nodes.get('Principled BSDF');p.inputs['Base Color'].default_value=(*linear,1)
    p.inputs['Roughness'].default_value=.88
    materials[name]=m

def reset():
    bpy.ops.object.select_all(action='SELECT');bpy.ops.object.delete(use_global=False)

def finish(o,mat,bevel=0):
    o.data.materials.append(materials[mat])
    if bevel:
        b=o.modifiers.new('Soft edges','BEVEL');b.width=bevel;b.segments=3
        b.affect='EDGES';bpy.context.view_layer.objects.active=o
        bpy.ops.object.modifier_apply(modifier=b.name)
    for p in o.data.polygons:p.use_smooth=True
    n=o.modifiers.new('Weighted normals','WEIGHTED_NORMAL');n.keep_sharp=True;n.weight=40
    bpy.context.view_layer.objects.active=o
    bpy.ops.object.modifier_apply(modifier=n.name)
    return o

def box(name,pos,size,mat,bevel=.06):
    bpy.ops.mesh.primitive_cube_add(size=1,location=pos);o=bpy.context.object;o.name=name
    o.dimensions=size;bpy.ops.object.transform_apply(location=False,rotation=False,scale=True)
    return finish(o,mat,min(bevel,min(size)*.42))

def cylinder(name,pos,radius,depth,mat,vertices=24):
    bpy.ops.mesh.primitive_cylinder_add(vertices=vertices,radius=radius,depth=depth,location=pos)
    o=bpy.context.object;o.name=name;return finish(o,mat,.035)

def sphere(name,pos,size,mat):
    bpy.ops.mesh.primitive_uv_sphere_add(segments=16,ring_count=8,radius=1,location=pos)
    o=bpy.context.object;o.name=name;o.scale=size
    bpy.ops.object.transform_apply(location=False,rotation=False,scale=True)
    return finish(o,mat)

def beam(name,a,b,radius,mat):
    a,b=Vector(a),Vector(b);o=cylinder(name,(a+b)/2,radius,(a-b).length,mat,12)
    o.rotation_euler=(b-a).to_track_quat('Z','Y').to_euler();return o

def rect_ring(name,w,d,r,z,h,thick,mat):
    verts=[];faces=[];steps=8
    def loop(ww,dd,rr,zz):
        for cx,cy,start in [(ww/2-rr,dd/2-rr,0),(-ww/2+rr,dd/2-rr,90),(-ww/2+rr,-dd/2+rr,180),(ww/2-rr,-dd/2+rr,270)]:
            for i in range(steps+1):
                a=math.radians(start+i*90/steps);verts.append((cx+rr*math.cos(a),cy+rr*math.sin(a),zz))
    loop(w,d,r,z);loop(w,d,r,z+h)
    loop(w-2*thick,d-2*thick,max(.1,r-thick),z+h)
    loop(w-2*thick,d-2*thick,max(.1,r-thick),z)
    n=4*(steps+1)
    for layer in range(4):
        for i in range(n):faces.append((layer*n+i,layer*n+(i+1)%n,((layer+1)%4)*n+(i+1)%n,((layer+1)%4)*n+i))
    mesh=bpy.data.meshes.new(name);mesh.from_pydata(verts,[],faces);mesh.update()
    o=bpy.data.objects.new(name,mesh);bpy.context.collection.objects.link(o);finish(o,mat,.025)
    return o

def tub(w,d,mat,private=False):
    rect_ring('Basin',w,d,min(w,d)*.32,.04,.8,.24,mat)
    rect_ring('Rim',w+.08,d+.08,min(w,d)*.32,.83,.13,.33,'cream' if private else mat)
    box('Basin floor',(0,0,.14),(w-.3,d-.3,.18),'teal',.2)
    box('Water',(0,0,.66),(w-.53,d-.53,.015),'water',.22)
    if not private:
        for yy in [-d*.3,d*.3]:box('Underwater bench',(0,yy,.35),(w*.62,.36,.22),mat)
    # Sculpted coping, low entry step, rolled towels and a little tray.
    box('Step',(0,-d/2-.25,.15),(w*.58,.52,.28),mat)
    box('Towel',(w*.22,-d/2,.97),(.5,.25,.13),'linen',.05)
    if mat=='cedar':
        rect_ring('Brass band',w+.035,d+.035,min(w,d)*.32,.23,.055,.08,'darkwood')
        rect_ring('Brass band',w+.035,d+.035,min(w,d)*.32,.6,.055,.08,'darkwood')
        for x in range(12):
            xx=-w*.4+x*w*.8/11
            box('Cedar stave',(xx,-d/2-.008,.46),(.012,.008,.6),'darkwood',0)
    if private:
        beam('Tap',(-w*.4,d*.24,.83),(-w*.4,d*.24,1.08),.04,'gold')
        beam('Tap',(-w*.4,d*.24,1.08),(-w*.4+.26,d*.24,1.08),.04,'gold')

def pavilion(w,d,mat='cream',roof=True):
    box('Room foundation',(0,0,.055),(w,d,.1),'stone')
    box('Wall back',(0,d/2-.1,1.27),(w,.18,2.5),mat)
    box('Wall side',(-w/2+.1,0,1.27),(.18,d,2.5),mat)
    box('Wall side',(w/2-.1,d*.25,1.27),(.18,d*.5,2.5),mat)
    for x in [-w/2+.12,w/2-.12]:
        box('Pillar',(x,-d/2+.12,1.22),(.22,.22,2.45),'wood')
    box('Lintel',(0,-d/2+.12,2.42),(w,.24,.24),'wood')
    if roof:
        # Sculpted gently curved roof, mirrored slopes. Matching model, not engine primitives.
        verts=[];faces=[];n=16
        for y in [-d/2-.27,d/2+.27]:
            for i in range(n+1):
                x=-w/2-.3+(w+.6)*i/n
                z=2.8+.53*math.cos(x/(w/2+.3)*math.pi/2)
                verts.append((x,y,z))
        for i in range(n):faces.append((i,i+1,n+2+i,n+1+i))
        m=bpy.data.meshes.new('roof');m.from_pydata(verts,[],faces);m.update()
        o=bpy.data.objects.new('Roof',m);bpy.context.collection.objects.link(o)
        s=o.modifiers.new('Roof thickness','SOLIDIFY');s.thickness=.13
        bpy.context.view_layer.objects.active=o;bpy.ops.object.modifier_apply(modifier=s.name)
        finish(o,'sage',.035)
        for yy in [-d/2-.27,d/2+.27]:
            for i in range(n):
                a=verts[i];b=verts[i+1]
                beam('Roof trim',(a[0],yy,a[2]-.04),(b[0],yy,b[2]-.04),.06,'wood')
        for i in range(12):
            yy=-d/2-.2+(d+.4)*i/11
            beam('Roof seam',(0,yy,3.35),(w/2+.3,yy,2.84),.02,'sage')
            beam('Roof seam',(0,yy,3.35),(-w/2-.3,yy,2.84),.02,'sage')

def export(name):
    # Merge authored pieces by material and visibility group. A sauna contains
    # many individual slats, but ships as a handful of meshes rather than 100 draws.
    groups={}
    for o in list(bpy.context.scene.objects):
        if o.type!='MESH':continue
        role='Water' if o.name.startswith('Water') else ('Roof' if o.name.startswith('Roof') else 'Body')
        mat=o.data.materials[0].name
        groups.setdefault((role,mat),[]).append(o)
    for (role,mat),pieces in groups.items():
        bpy.ops.object.select_all(action='DESELECT')
        for o in pieces:o.select_set(True)
        bpy.context.view_layer.objects.active=pieces[0]
        bpy.ops.object.join()
        o=bpy.context.object;o.name=role+'_'+mat
        bpy.ops.object.transform_apply(location=True,rotation=True,scale=True)
    bpy.ops.object.select_all(action='SELECT')
    bpy.ops.export_scene.gltf(filepath=str(OUT/(name+'.glb')),export_format='GLB',export_yup=True,export_apply=True,export_extras=False)
    print('AUTHORED',name,flush=True)

reset();box('Stone tile',(0,0,-.1),(1.8,1.8,.2),'cream',.04);export('floor_stone')
reset();box('Cedar tile',(0,0,-.1),(1.8,1.8,.2),'cedar',.04)
for i in range(6):box('Floor board joint',(-.75+i*.3,0,.004),(.008,1.72,.008),'wood',0)
export('floor_wood')
reset();box('Garden tile',(0,0,-.15),(1.8,1.8,.29),'grass',.07);export('floor_garden')
reset();box('Diorama',(0,0,-.6),(46,39,1.15),'earth',1.1);box('Soft meadow',(0,0,-.18),(46.04,39.04,.33),'grass',.6);export('island')
reset();tub(3.7,3.7,'cedar');export('hot_tub')
reset();tub(2.5,2.5,'stone');export('plunge')
reset();tub(2,3.7,'linen',True);export('private_bath')
reset();tub(3.5,2.5,'stone',True);export('stone_bath')
reset();tub(6.8,3.6,'cream');export('mineral_pool')
reset();pavilion(4.9,4.9,'sage')
for y in [1.75,.95]:box('Bench',(0,y,.48),(4.3,.6,.36),'cedar')
for x in range(8):box('Tile',(x*.55-1.94,2.35,1.85),(.5,.025,.5),'cream')
cylinder('Bowl',(0,0,.42),.43,.52,'stone');export('steam_room')
reset();pavilion(4.9,4.9,'cedar')
for yy in [.85,1.65]:
    box('Sauna bench',(0,yy,.52),(4.25,.65,.25),'wood')
    for i in range(9):box('Bench slat',(-1.9+i*.47,yy,.67),(.42,.62,.1),'cedar')
for i in range(12):box('Timber wall joint',(-2.2+i*.4,2.35,1.2),(.018,.014,2.2),'wood',0)
cylinder('Heater',(1.55,-1.3,.5),.4,.9,'charcoal')
for i in range(7):sphere('Sauna stone',(1.55+random.uniform(-.24,.24),-1.3+random.uniform(-.24,.24),.96),(.17,.15,.12),'stone')
export('sauna')
reset();pavilion(3.15,3.15)
cylinder('Toilet base',(.6,.65,.23),.26,.46,'linen');sphere('Porcelain',(.6,.54,.54),(.39,.53,.23),'linen')
box('Cistern',(.6,1.17,.7),(.7,.3,.75),'linen');box('Sink',(-.65,.88,.9),(.8,.65,.2),'linen')
beam('Tap',(-.65,1.06,.96),(-.65,1.06,1.2),.025,'gold');export('bathroom')
reset();pavilion(4.9,3.15,'cream')
for i in range(6):
    x=-1.9+i*.76;box('Locker',(x,1.18,1.04),(.71,.54,2),'sage' if i%2==0 else 'cedar')
    box('Handle',(x+.18,.888,1.05),(.045,.07,.22),'gold')
box('Changing bench',(0,-.45,.47),(3.3,.6,.16),'wood')
for x in [-1.25,1.25]:box('Bench leg',(x,-.45,.23),(.13,.45,.45),'darkwood')
export('changing')
reset();box('Shower tray',(0,0,.05),(1.4,2.7,.1),'cream');box('Privacy wall',(0,1.2,1.2),(1.4,.18,2.4),'sage')
beam('Shower riser',(0,1.05,.8),(0,1.05,2.25),.04,'gold');beam('Shower arm',(0,1.05,2.25),(0,.35,2.25),.04,'gold')
cylinder('Rain head',(0,.35,2.24),.25,.08,'gold');cylinder('Drain',(0,.35,.11),.09,.012,'gold');export('shower')
reset();pavilion(6.6,4.9,'cream');export('relaxation')
reset();box('Reception desk',(0,0,.62),(4.25,1.25,1.23),'cedar',.16)
box('Countertop',(0,0,1.28),(4.45,1.4,.15),'cream')
for x in range(14):box('Front slat',(-1.97+x*.303,-.642,.6),(.11,.08,1.02),'wood')
box('Register',(1.23,.2,1.5),(.48,.34,.3),'charcoal')
box('Welcome book',(-.4,0,1.42),(.6,.38,.13),'linen');export('reception')
reset();pavilion(5,3.5,'cream',False);export('cafe_shell')
reset();box('Daybed',(0,0,.48),(1.35,2.9,.25),'cedar');box('Linen cushion',(0,-.1,.68),(1.21,2.5,.2),'linen',.15)
o=box('Back cushion',(0,.96,.95),(1.24,.6,.21),'sage',.1);o.rotation_euler.x=-.5
for x in [-.5,.5]:
 for y in [-1.04,1.04]:box('Daybed leg',(x,y,.25),(.12,.15,.5),'wood')
export('lounger')
reset();beam('Stand',(-.5,0,0),(-.5,0,2.2),.075,'wood');beam('Arm',(-.5,0,2.2),(.4,0,2.2),.075,'wood')
cylinder('Bucket',(.4,0,1.72),.35,.49,'cedar')
for z in [1.55,1.87]:cylinder('Bucket band',(.4,0,z),.36,.04,'darkwood')
box('Drip tray',(.25,0,.035),(1.25,1.2,.08),'stone');export('ice_bucket')
reset();box('Planter',(0,0,.32),(2.95,1.15,.64),'cream',.17)
for i in range(4):
 x=-1.1+i*.72
 for j in range(5):
  a=j*math.tau/5;beam('Stem',(x,0,.59),(x+math.cos(a)*.23,math.sin(a)*.22,.85),.023,'leaf')
  sphere('Leaf',(x+math.cos(a)*.25,math.sin(a)*.24,.85),(.23,.15,.095),'leaf')
export('planter')
reset();cylinder('Pot',(0,0,.23),.34,.46,'clay')
beam('Tree stem',(0,0,.4),(.05,0,1.45),.045,'wood')
for i in range(5):
 a=i*math.tau/5;beam('Branch',(.02,0,.9),(.45*math.cos(a),.4*math.sin(a),1.5+i*.055),.028,'wood')
 sphere('Leaves',(.4*math.cos(a),.38*math.sin(a),1.47+i*.055),(.44,.4,.34),'sage' if i%2 else 'leaf')
sphere('Leaves',(0,0,1.82),(.5,.45,.38),'leaf');export('potted_tree')
reset();cylinder('Pot',(0,0,.25),.38,.5,'cream');beam('Stem',(0,0,.4),(0,0,1.65),.04,'wood')
for i in range(9):
 a=i*math.tau/9
 o=sphere('Palm frond',(.5*math.cos(a),.5*math.sin(a),1.6),(.78,.1,.14),'leaf');o.rotation_euler.z=a;o.rotation_euler.y=.28
export('palm')
reset();box('Stone surround',(0,0,.16),(2.8,2.8,.3),'cream',.3);cylinder('Fountain bowl',(0,0,.49),1.1,.75,'stone')
cylinder('Water',(0,0,.9),.95,.02,'water');cylinder('Fountain pedestal',(0,0,1.11),.13,.5,'cream');sphere('Fountain cap',(0,0,1.43),(.32,.32,.16),'cream');export('fountain')
reset();box('Wall',(0,0,1.26),(1.8,.18,2.52),'cream');box('Coping',(0,0,2.54),(1.87,.25,.1),'wood');export('wall')
reset();box('Low wall',(0,0,.34),(1.8,.18,.68),'cream');box('Coping',(0,0,.7),(1.87,.25,.1),'wood');export('low_wall')
reset()
for x in [-.75,.75]:box('Gate pillar',(x,0,1.12),(.25,.3,2.24),'wood')
box('Arch lintel',(0,0,2.22),(1.8,.32,.26),'wood')
for x in [-.52,.52]:
 o=box('Arch brace',(x,0,2.03),(.65,.2,.12),'wood');o.rotation_euler.y=0;o.rotation_euler.z=.64 if x<0 else -.64
export('arch')
reset();pavilion(5.25,5.25,'cream');export('pavilion')
reset();sphere('Boulder',(0,0,.25),(.7,.5,.48),'stone');export('rock')
print('Spa kit complete.',flush=True)
