"""Export Godot and package a self-contained local HTML plus the public website."""
import base64, hashlib, html, json, os, pathlib, re, shutil, subprocess, zipfile

ROOT=pathlib.Path(__file__).resolve().parents[1]
PROJECT=ROOT/'godot'; EXPORT=PROJECT/'export'; SITE=ROOT/'_site'
env=os.environ.copy()
env.update(XDG_DATA_HOME=str(ROOT.parent/'.godot-data'),XDG_CONFIG_HOME=str(ROOT.parent/'.godot-config'),XDG_CACHE_HOME='/tmp/stillwater-cache')
subprocess.run(['python3',str(ROOT/'tools/bootstrap-godot.py')],env=env,check=True)
assets=PROJECT/'assets'
records=[{'file':str(p.relative_to(assets)),'sha256':hashlib.file_digest(p.open('rb'),'sha256').hexdigest(),'bytes':p.stat().st_size} for p in sorted(assets.rglob('*')) if p.is_file() and not p.name.endswith('.import') and p.name!='manifest.json']
(assets/'manifest.json').write_text(json.dumps(records,indent=2)+'\n')
EXPORT.mkdir(exist_ok=True)
# Export requires current imported scenes and scripts, not a stale editor cache.
for args in [['--editor','--import'],['--export-release','Web','export/index.html']]:
    result=subprocess.run(['godot','--headless','--path',str(PROJECT),*args],env=env,capture_output=True,text=True)
    log=result.stdout+result.stderr
    (pathlib.Path('/tmp')/('stillwater-import.log' if '--import' in args else 'stillwater-export.log')).write_text(log)
    if result.returncode or 'SCRIPT ERROR:' in log or '\nERROR:' in log:
        print(log[-10000:]);raise SystemExit('Godot import/export failed; see /tmp/stillwater-*.log.')
print('Godot browser build exported.',flush=True)

if SITE.exists():
    if not (SITE/'.stillwater-site').exists():raise SystemExit('Refusing to replace an unmarked _site directory.')
    shutil.rmtree(SITE)
SITE.mkdir();(SITE/'.stillwater-site').write_text('Generated by tools/build.py\n');(SITE/'.nojekyll').write_text('')
for p in EXPORT.iterdir():
    if p.is_file():shutil.copy(p,SITE/p.name)
for name in ['thumbnails','licenses']:
    if (ROOT/'web'/name).exists():shutil.copytree(ROOT/'web'/name,SITE/name)
for name in ['credits.html','download.html']:
    if (ROOT/'web'/name).exists():shutil.copy(ROOT/'web'/name,SITE/name)
for name in ['preview.png','preview-roofs.png','preview-detail.png']:
    if (ROOT/name).exists():shutil.copy(ROOT/name,SITE/name)

# Keep the earlier game available at /classic/ with its existing save origin.
if (ROOT/'legacy/index.html').exists():
    classic=SITE/'classic';classic.mkdir()
    for name in ['index.html','engine.js','model-library.js','architecture.js','asset-data.js']:
        shutil.copy(ROOT/'legacy'/name,classic/name)
    for name in ['three.min.js','babylon.js','babylon.glTFFileLoader.min.js']:
        (classic/'vendor').mkdir(exist_ok=True);shutil.copy(ROOT/'legacy/vendor'/name,classic/'vendor'/name)
    shutil.copytree(ROOT/'legacy/assets',classic/'assets',ignore=shutil.ignore_patterns('*.glb','*.zip','*.hdr'))
    for p in (ROOT/'legacy/vendor').glob('*LICENSE*'):shutil.copy(p,classic/'vendor'/p.name)
    shutil.copy(ROOT/'legacy/vendor/Apache-2.0.txt',classic/'vendor/Apache-2.0.txt')

# The native export's fetches are served from embedded byte buffers in the local
# HTML. AudioWorklets use blob URLs through Godot's documented locator hook.
# Neither the engine binary nor its rendering implementation is modified.
payload={}
for p in [*EXPORT.iterdir(),*(ROOT/'web/thumbnails').glob('*.png')]:
    if p.suffix in ['.wasm','.pck','.png'] or p.name.endswith('.worklet.js'):
        name=p.name if p.parent==EXPORT else 'thumbnails/'+p.name
        payload[name]=base64.b64encode(p.read_bytes()).decode()
bridge='''<script>
const spaEmbedded=__FILES__;
const spaBuffers=new Map(),spaUrls=new Map();
function spaBytes(name){if(!spaBuffers.has(name)){const b=atob(spaEmbedded[name]),u=new Uint8Array(b.length);for(let i=0;i<b.length;i++)u[i]=b.charCodeAt(i);spaBuffers.set(name,u)}return spaBuffers.get(name)}
function spaMime(name){return name.endsWith('.wasm')?'application/wasm':name.endsWith('.png')?'image/png':name.endsWith('.js')?'text/javascript':'application/octet-stream'}
window.spaAssetUrl=name=>{if(!spaEmbedded[name])return name;if(!spaUrls.has(name))spaUrls.set(name,URL.createObjectURL(new Blob([spaBytes(name)],{type:spaMime(name)})));return spaUrls.get(name)};
const spaFetch=window.fetch.bind(window);
window.fetch=(input,options)=>{const u=typeof input==='string'?input:input.url;const name=new URL(u,location.href).pathname.split('/').pop();if(spaEmbedded[name]){const bytes=spaBytes(name);return Promise.resolve(new Response(bytes,{status:200,headers:{'Content-Type':spaMime(name),'Content-Length':String(bytes.length)}}))}return spaFetch(input,options)};
</script>'''.replace('__FILES__',json.dumps(payload,separators=(',',':')))
source=(EXPORT/'index.html').read_text()
source=source.replace('<script src="index.js"></script>',bridge+'\n<script>\n'+(EXPORT/'index.js').read_text().replace('</script','<\\/script')+'\n</script>')
source=source.replace('const missing=Engine.getMissingFeatures', '''const spaModuleConfig=engine.config.getModuleConfig.bind(engine.config);
engine.config.getModuleConfig=(...args)=>{const config=spaModuleConfig(...args),locate=config.locateFile;config.locateFile=file=>window.spaAssetUrl(locate(file));return config};
const missing=Engine.getMissingFeatures''')
source=source.replace('href="download.html"','href="https://markbobthomas.github.io/spa/download.html"').replace('href="classic/"','href="https://markbobthomas.github.io/spa/classic/"')
source='<!-- Stillwater: Godot MIT license and CC0 asset credits accompany this file in the ZIP. -->\n'+source
(ROOT/'Stillwater.html').write_text(source)

with zipfile.ZipFile(ROOT/'Stillwater.zip','w',compression=zipfile.ZIP_DEFLATED,compresslevel=9) as z:
    z.write(ROOT/'Stillwater.html','Stillwater.html')
    z.write(ROOT/'README.md','START-HERE.md')
    for p in (ROOT/'web/licenses').glob('*'):z.write(p,'licenses/'+p.name)
    credits=(ROOT/'web/credits.html').read_text().replace('href="index.html"','href="Stillwater.html"').replace('href="Stillwater-Godot-project.zip"','href="https://markbobthomas.github.io/spa/Stillwater-Godot-project.zip"').replace('href="classic/"','href="https://markbobthomas.github.io/spa/classic/"')
    z.writestr('credits.html',credits)
shutil.copy(ROOT/'Stillwater.zip',SITE/'Stillwater.zip')
# An editable native engine project is also a concrete deliverable.
with zipfile.ZipFile(SITE/'Stillwater-Godot-project.zip','w',compression=zipfile.ZIP_DEFLATED) as z:
    for folder in ['godot','web','tools','tests']:
        for p in (ROOT/folder).rglob('*'):
            rel=p.relative_to(ROOT)
            if p.is_file() and '.godot' not in rel.parts and 'export' not in rel.parts and '__pycache__' not in rel.parts:z.write(p,str(rel))
    z.write(ROOT/'README.md','README.md')
hashes={str(p.relative_to(SITE)):hashlib.file_digest(p.open('rb'),'sha256').hexdigest() for p in sorted(SITE.rglob('*')) if p.is_file()}
(SITE/'site-manifest.json').write_text(json.dumps(hashes,indent=2)+'\n')
for name in ['index.js','index.wasm','index.pck']:
    if not (SITE/name).exists():raise SystemExit('Missing export file '+name)
with zipfile.ZipFile(ROOT/'Stillwater.zip') as z:
    if hashlib.sha256(z.read('Stillwater.html')).hexdigest()!=hashlib.file_digest((ROOT/'Stillwater.html').open('rb'),'sha256').hexdigest():raise SystemExit('Offline archive integrity check failed.')
print('Built and verified the website, offline HTML ZIP, and editable Godot project.',flush=True)
print('Offline ZIP: %.1f MB; browser assets: %.1f MB'%((ROOT/'Stillwater.zip').stat().st_size/1e6,sum(p.stat().st_size for p in EXPORT.iterdir())/1e6))
