// Build a public static site containing only the game and its downloadable files.
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const {execFileSync} = require('node:child_process');
const root = path.resolve(__dirname, '..');
const out = path.join(root, '_site');
execFileSync(process.execPath, [path.join(__dirname, 'package.cjs')], {cwd:root, stdio:'inherit'});
execFileSync('python3', [path.join(__dirname, 'download.py')], {cwd:root, stdio:'inherit'});
if (fs.existsSync(out)) {
  if (!fs.existsSync(path.join(out, '.stillwater-site'))) throw Error('Existing _site directory is not a generated Stillwater site.');
  fs.rmSync(out, {recursive:true});
}
fs.mkdirSync(out, {recursive:true});
fs.writeFileSync(path.join(out, '.stillwater-site'), 'Generated by tools/site.cjs\n');
const files = [
  'index.html', 'engine.js', 'model-library.js', 'architecture.js', 'asset-data.js',
  'vendor/three.min.js', 'vendor/babylon.js', 'vendor/babylon.glTFFileLoader.min.js',
  'vendor/THREE-LICENSE.txt', 'vendor/Apache-2.0.txt',
  'assets/SOURCES.md', 'assets/CC-BY-4.0.txt', 'assets/CC0-1.0.txt',
  'Stillwater.html', 'Stillwater.zip', 'examples/island-retreat.json',
  'preview.png', 'preview-cutaway.png', 'preview-detail.png',
];
const hashes = {};
for (const file of files) {
  const target = path.join(out, file);
  fs.mkdirSync(path.dirname(target), {recursive:true});
  fs.copyFileSync(path.join(root, file), target);
  const original = crypto.createHash('sha256').update(fs.readFileSync(path.join(root, file))).digest('hex');
  const copied = crypto.createHash('sha256').update(fs.readFileSync(target)).digest('hex');
  if (original !== copied) throw Error('Site copy differs: '+file);
  hashes[file] = copied;
}
fs.writeFileSync(path.join(out, '.nojekyll'), '');
fs.writeFileSync(path.join(out, 'site-manifest.json'), JSON.stringify(hashes, null, 2)+'\n');
fs.writeFileSync(path.join(out, 'download.html'), `<!doctype html>
<html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Stillwater — play and download</title>
<style>body{margin:0;background:#ecf0e7;color:#2c493e;font:17px/1.6 system-ui,sans-serif}main{max-width:740px;margin:7vh auto;padding:24px}h1{font:48px Georgia,serif}a{color:#355d46}a.button{display:inline-block;margin:8px 10px 8px 0;padding:13px 22px;background:#355d46;color:white;border-radius:10px;text-decoration:none}img{width:100%;border-radius:16px}small{display:block;margin-top:20px}</style>
<main><h1>Stillwater</h1><p>A quiet little world to build your own spa.</p>
<a class="button" href="index.html">Play in your browser</a>
<a class="button" href="Stillwater.zip" download>Download the offline game · 13 MB</a>
<p>To play offline, extract the ZIP and open <b>Stillwater.html</b> in your browser. Everything is included.</p>
<img src="preview-cutaway.png" alt="The Stillwater island spa with cutaway roofs, pools, plants, and guests">
<small>Drag to orbit · Scroll to zoom · R rotates furnishings · C changes roofs · P opens photo view.</small>
<p><a href="examples/island-retreat.json" download>Download the example resort</a> and import it through the game’s menu.</p></main></html>`);
const html = fs.readFileSync(path.join(out, 'index.html'), 'utf8');
for (const match of html.matchAll(/<script\s+src="([^"]+)"/g)) {
  const target = path.resolve(out, match[1]);
  if (!target.startsWith(out+path.sep) || !fs.existsSync(target)) throw Error('Missing or external site script: '+match[1]);
}
console.log('Built and verified _site: browser game, offline download, example, previews, and credits.');
